APP_NAME = "graver"
FINDAGRAVE_BASE_URL: str = "https://www.findagrave.com"
FINDAGRAVE_ROWS_PER_PAGE: int = 20
MEMORIAL_CANONICAL_URL_FORMAT: str = FINDAGRAVE_BASE_URL + "/memorial/{}"
CEMETERY_CANONICAL_URL_FORMAT: str = FINDAGRAVE_BASE_URL + "/cemetery/{}"
