[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "graver"
dynamic = ["version", "description"]
authors = [{ name = "Larry McQueary", email = "contact@mcqueary.org" }]
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.8"
dependencies = ["beautifulsoup4==4.12.2", "lxml==4.9.3", "tqdm==4.66.1", "typer==0.9.0"]

[project.optional-dependencies]
lint = ["black", "flake8", "isort"]
test = ["pytest", "faker", "coverage", "pytest-cov", "coveralls"]

[project.urls]
Home = "https://github.com/mcqueary/graver"

[project.scripts]
graver = "graver.cli:app"

[tool.setuptools.dynamic]
version = {attr = "package.__version__"}