[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "graver"
authors = [{ name = "Larry McQueary", email = "contact@mcqueary.org" }]
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.7"
dynamic = ["version", "description"]
dependencies = ["bs4==0.0.1", "tqdm==4.66.1"]

[project.optional-dependencies]
lint = ["black", "flake8", "prettier", "isort"]
test = ["pytest", "faker", "tox", "coverage", "pytest-cov", "coveralls"]

[project.urls]
Home = "https://github.com/mcqueary/graver"

[project.scripts]
graver = "graver.cli:app"
